### ISSUE TITLE
Email from GMAIL with inline pasted image - error

### ISSUE THREAD

**Issue by arnisjuraga** [credativUK/redmine_email_inline_images#1]
Hi! Nice plugin, ...but....

1) tested with e-mail sen from Postbox client with IMAP to gmail, and plugin did not include inline images, but attached as attachments.

2) then tested with native Gmail new compose interface - sent message, but receiving e-mail generated error:

```
** Invoke redmine:email:receive_imap (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:email:receive_imap
rake aborted!
undefined method `element' for <ii_1439193614e4d2f6>:Mail::UnstructuredField
/var/lib/gems/1.9.1/gems/mail-2.5.4/lib/mail/field.rb:167:in `method_missing'
/opt/redmine/redmine-ri-2.4.0/plugins/redmine_email_inline_images/lib/mail_handler_patch.rb:24:in `block in plain_text_body_with_email_inline_images'
/opt/redmine/redmine-ri-2.4.0/plugins/redmine_email_inline_images/lib/mail_handler_patch.rb:22:in `each'
/opt/redmine/redmine-ri-2.4.0/plugins/redmine_email_inline_images/lib/mail_handler_patch.rb:22:in `plain_text_body_with_email_inline_images'
/opt/redmine/redmine-ri-2.4.0/app/models/mail_handler.rb:312:in `get_keyword'
/opt/redmine/redmine-ri-2.4.0/app/models/mail_handler.rb:363:in `issue_attributes_from_keywords'
/opt/redmine/redmine-ri-2.4.0/app/models/mail_handler.rb:186:in `receive_issue'
/opt/redmine/redmine-ri-2.4.0/app/models/mail_handler.rb:174:in `dispatch_to_default'
/opt/redmine/redmine-ri-2.4.0/app/models/mail_handler.rb:159:in `dispatch'
/opt/redmine/redmine-ri-2.4.0/app/models/mail_handler.rb:134:in `receive'
/var/lib/gems/1.9.1/gems/actionmailer-3.2.15/lib/action_mailer/base.rb:404:in `block in receive'
/var/lib/gems/1.9.1/gems/activesupport-3.2.15/lib/active_support/notifications.rb:123:in `block in instrument'
/var/lib/gems/1.9.1/gems/activesupport-3.2.15/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.9.1/gems/activesupport-3.2.15/lib/active_support/notifications.rb:123:in `instrument'
/var/lib/gems/1.9.1/gems/actionmailer-3.2.15/lib/action_mailer/base.rb:401:in `receive'
/opt/redmine/redmine-ri-2.4.0/app/models/mail_handler.rb:46:in `receive'
/opt/redmine/redmine-ri-2.4.0/lib/redmine/imap.rb:35:in `block in check'
/opt/redmine/redmine-ri-2.4.0/lib/redmine/imap.rb:32:in `each'
/opt/redmine/redmine-ri-2.4.0/lib/redmine/imap.rb:32:in `check'
/opt/redmine/redmine-ri-2.4.0/lib/tasks/email.rake:125:in `block (3 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:email:receive_imap
www-data@redmine:~$ /etc/scripts/redmine_support_ielase.sh
** Invoke redmine:email:receive_imap (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:email:receive_imap

```

Have ideas?

**Comment by DJUserkent** [comment]
Some people have it working fine:  check the reviews at the bottom of the page:
-   http://www.redmine.org/plugins/redmine_helpdesk

**Comment by s-andy** [comment]
@arnisjuraga, I got the same error (for inline images, that were inserted in GMail).

I managed to fix this in my fork in the following commit: https://github.com/s-andy/redmine_email_inline_images/commit/1c56d1b0b266d64a85b0b9c6bb6a89a77595c7e3
